#!/bin/bash

ifconfig eth0 up
ifconfig eth0 172.16.20.254
route add -net 172.16.20.0/24 gw 172.16.20.1 eth0

ifconfig eth1 up
ifconfig eth1 172.16.21.253
route add -net 172.16.21.0/24 gw 172.16.21.1 eth1

echo 1 > /proc/sys/net/ipv4/ip_forward
echo 0 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts

chmod +x 7-joao-ana-ricardo_4
