#!/bin/bash

ifconfig eth0 up
ifconfig eth0 172.16.21.1/24
#route add -net 172.16.20.0/24 gw 172.16.21.253
route add -net 172.16.20.0/24 gw 172.16.21.254
route add default gw 172.16.21.254

#echo 0 > /proc/sys/net/ipv4/conf/eth0/accept_redirects
#echo 0 > /proc/sys/net/ipv4/conf/all/accept_redirects

chmod +x 7-ana-joao-ricardo-2
